### ISSUE TITLE
Migrate to Swift 4

### ISSUE THREAD

**Issue by serralvo** [serralvo/TextFieldCounter#13]
Before #12

**Comment by darthpelo** [comment]
@serralvo I'm working on :)

**Comment by darthpelo** [comment]
@serralvo I will create the PR first of October (Hacktoberfest counts PR from 1st to 31st October only)

**Comment by serralvo** [comment]
@darthpelo Ok, no problem, I'll try release version 1.0 before 😄

**Comment by serralvo** [comment]
Thanks @darthpelo
