### ISSUE TITLE
Setting UITextFieldDelegate in ViewController for the custom TextField

### ISSUE THREAD

**Issue by patricks** [serralvo/TextFieldCounter#16]
If I set the `UITextFieldDelegate` in my own ViewController, the TextFieldCounter class doesn't get any delegate callbacks from `UITextFieldDelegate` and so it doesn't work anymore.

Is it possible to support both delegates?

**Comment by filletofish** [comment]
Hi @patricks,
Thank you for pointing this out.

Yes this is possible. There are two options:
1.  Expand `TextFieldCounterDelegate` with functions from `UITextFieldDelegate` and forward all delegate calls to counterDelegate.
2. Override var `delegate` in such way that setting would set only private var `userDelegate` (or better name). Then in all delegate calls inside TextFieldCounter forward them to `userDelegate`.

Second option is more preferable I suppose. 

```swift
private weak var userDelegate: UITextFieldDelegate?

override weak var delegate: UITextFieldDelegate? {
  set {  self.userDelegate = newValue }
  get { return self.userDelegate }
}
```

and forwarding:
```swift
func textFieldDidEndEditing(_ textField: UITextField) {
    // Our custom logic
    return self.delegate?. textFieldDidEndEditing(self)
}
```

I suppose we can forward even`textField(_:shouldChangeCharactersIn:replacementString:)`, this is open question.

**Comment by rogerluan** [comment]
What's usually done when combining `textField(_:shouldChangeCharactersIn:replacementString:)` (or any delegate that returns a `Bool`), is perform a `&&` for all the return values :)

**Comment by serralvo** [comment]
@patricks 

I'm on it.

**Comment by serralvo** [comment]
@patricks 

Added in 1.0.2 version.
