### ISSUE TITLE
Use of undeclared type 'TextFieldCounter'

### ISSUE THREAD

**Issue by Maryom** [serralvo/TextFieldCounter#7]
Hey,

Thanks for your awesome repo. I installed the latest version `Installing TextFieldCounter (0.0.2)`
and I imported it `import TextFieldCounter` however, I got this error:

<img width="810" alt="screen shot 2017-05-11 at 10 33 51 am" src="https://cloud.githubusercontent.com/assets/3218401/25937837/e5c977ac-3635-11e7-8f82-ee553fea2de1.png">

What is the problem?!

Thanks.

**Comment by serralvo** [comment]
Hi @Maryom, 

Sorry for this problem, I'll try fix it as soon as possible.

Thanks.

**Comment by serralvo** [comment]
Hello @Maryom,

I did some changes (special thanks to @ciceroduarte  👍) and looks ok, can you verify if is everything ok?

<img width="487" alt="screen shot 2017-05-11 at 23 27 12" src="https://cloud.githubusercontent.com/assets/4379570/25979873/662b4c52-36a1-11e7-8c61-5d6074d6095e.png">

**Comment by Maryom** [comment]
Hey,

I checked and it worked perfectly. Thanks for your efforts 🙏🏼
