### ISSUE TITLE
Pod version outdated

### ISSUE THREAD

**Issue by AndresCianio** [serralvo/TextFieldCounter#9]
It seems the version in the cocoapods repo is outdated, as the class is not `open`. 
This causes that when importing the module, the class can't actually be used.
Would be great to fix it!! In the meantime I'll work against the repo master branch.

**Comment by serralvo** [comment]
Hello @AndresCianio 

Which version are you using? We fixed this issue in `0.0.3` (was reported in #7 ), can you check the version in your pod file?

Thanks

**Comment by AndresCianio** [comment]
Hi @serralvo thanks for the reply ;)

In my podfile I have `pod 'TextFieldCounter'`.
While installing the log says `Installing TextFieldCounter (0.0.1)`.
Double checking the Podfile.lock, it says `  - TextFieldCounter (0.0.1)`.

**Comment by serralvo** [comment]
Hello @AndresCianio 

Can you try using version `0.0.3`? `pod 'TextFieldCounter', '0.0.3'`

Thanks

**Comment by AndresCianio** [comment]
All right.... So I tried it but it didn't work either.

However, after `pod repo update` (which no longer happens automatically :/) it worked just fine. Removed the version and *voilá* it is all working as expected.

Thanks for the help! Closing as the problem was on my end.
